" Start of Vundle.vim (plugin manager)

set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'Valloric/YouCompleteMe'

call vundle#end()
filetype plugin indent on

" Brief help
" :PluginList - lists configured plugins
" :PluginInstall - installs plugins; append '!' to update or just
" :PluginUpdate
" :PluginSearch foo - searches for foo; append '!' to refresh local cache 
" :PluginClean - confirms removal of unused plugins; append '!' to
" auto-approve removal

" End of Vundle.vim (plugin manager)

" Navigate thru tabs
map <C-t><left> :tabp<cr>
map <C-t><right> :tabn<cr>

" Nice to have for syntax
syntax enable 

set background=dark

" This is for colorscheme so background looks clear.
hi Normal ctermbg=none
highlight NonText ctermbg=none
colorscheme default

filetype plugin indent on

set tabstop=4
set softtabstop=4 noexpandtab
set shiftwidth=4
set number
set relativenumber
set noswapfile
set clipboard=unnamedplus
set autoread

autocmd BufRead,BufNewFile   *.c,*.cpp,*.h,*.java set noic cin noexpandtab

" Powerlines
set rtp+=/usr/local/lib/python3.6/dist-packages/powerline/bindings/vim/
set laststatus=2
set t_Co=256
