set nocompatible
filetype off

" Navigate thru tabs
map <C-t><left> :tabp<cr>
map <C-t><right> :tabn<cr>

" Nice to have for syntax
syntax enable 

set background=dark

" This is for colorscheme so background looks clear.
hi Normal ctermbg=none
highlight NonText ctermbg=none
colorscheme default

filetype plugin indent on

set tabstop=4
set softtabstop=4 noexpandtab
set shiftwidth=4
set number
set relativenumber
set noswapfile
set clipboard=unnamedplus
set autoread

autocmd BufRead,BufNewFile   *.c,*.cpp,*.h,*.java set noic cin noexpandtab

" Enabling to list characters
:set listchars=eol:¬,tab:>-,trail:~,extends:>,precedes:<,space:·
noremap <F5> :set nolist!<CR>
inoremap <F5> <C-o>:set nolist!<CR>
cnoremap <F5> <c-c>:set nolist!<CR>