# Alias for tso.sh (Tmux Session Opener)
alias tso='~/Documents/GitRepos/MyRepo/dotfiles/scripts/./tso.sh'

# Alias for tmux_init.sh (Tmux panes initializer).
alias tmux_init='~/Documents/GitRepos/MyRepo/dotfiles/scripts/./tmux_init.sh'

# Alias for disableTouchpad.sh (Disables touchpad if mouse is present).
alias disableTouchpad='~/Documents/GitRepos/MyRepo/dotfiles/scripts/./disableTouchpad.sh'

# Alias for decelerateMouse.sh (Decelerate mouse).
alias decelerateMouse='~/Documents/GitRepos/MyRepo/dotfiles/scripts/./decelerateMouse.sh'
